language: objective-c
osx_image: xcode7.3
xcode_workspace: xikolo-ios.xcworkspace
xcode_scheme: xikolo-ios

env:
  - SCHEME="xikolo-ios" SDK="iphonesimulator"
  - SCHEME="xikolo-tvos" SDK="appletvsimulator"

script:
  - xctool -workspace xikolo-ios.xcworkspace -scheme $SCHEME -sdk $SDK build
